### ISSUE TITLE
How hard would it be to integrate your telnet library with DGD

### ISSUE THREAD

**Issue by evilmog** [KazDragon/telnetpp#219]
Hi There, I'm ok at LPC, terrible at C++.  How hard would it be to integrate this library to give full support for various protocols into DGD.

DGD is the driver for some variants of LPMuds. https://github.com/dworkin/dgd

It would require some LPC side hooks which I would be willing to do, its the c++ driver source I can't figure out.

**Comment by KazDragon** [comment]
Hi evilmog.  I appreciate you taking the time out to have a look at my library.

For integrating the library itself as handling the all the Telnet negotiations for you, I'd hope this wouldn't take more than a few hours.  It looks as though dgd doesn't have external dependencies, so sorting that mechanism out would be the first thing, since Telnet++ has a couple that it needs (Boost, gsl-lite).  

It really up to you on how you want to approach this.  E.g. a simple way to do things might be to fork dgd, add Telnet++ as a submodule, and edit the makefile to add Telnet++'s own source files.  Assuming you've installed Boost and gsl-lite locally, this Should Just Work (tm).

Alternatively, you could fork dgd and turn it into a CMake project.  Then you could add a conanfile.txt announcing Telnet++ as a dependency and hook that into the CMakeLists.txt (similar to how my example projects do it).

Integrating Telnet++ so that it handles the negotiations itself would be the next step.  And then deciding what protocols you need.  Telnet++ has most common options already, but there are some mud-specific ones that aren't implemented out-of-the-box (e.g. GMCP).
